version: 2
jobs:
  doc-build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: prep environment & make docs
          command: |
            python3 -m venv doc-env
            . doc-env/bin/activate
            pip install -r requirements_doc.txt --progress-bar off
            pip install .
            cd docs
            make html
      - store_artifacts:
          path: doc/_build/html
workflows:
  version: 2
  push:
    jobs:
      - doc-build
